name: Agents Schema Cube

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  agents-schema-cube:
    uses: fivetran/agents_schema/.github/workflows/agents-schema-cube.yml@v0.0.6
    with:
      metadata-path: metadata/cube-meta.json
    secrets: inherit
