name: Agents Schema Tableau

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  agents-schema-tableau:
    uses: fivetran/agents_schema/.github/workflows/agents-schema-tableau.yml@v0.0.6
    with:
      metadata-path: metadata/tableau-metadata.json
    secrets: inherit
